volumes:
  audiobase_database:
  audiobase_elasticsearch:

networks:
  dev:
    driver: bridge

services:
  audiobase_db:
    image: postgres:latest
    container_name: audiobase_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5433:5432"
    networks:
      - dev
    restart: always
    volumes:
      - audiobase_database:/var/lib/postgresql/data
  audiobase_redis:
    image: redis:latest
    container_name: audiobase_redis
    networks:
      - dev
    volumes:
      - /path/to/local/data:/root/redis
      - /path/to/local/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
  audiobase_elasticsearch:
    container_name: audiobase_elasticsearch
    image: elasticsearch:8.11.3
    ports:
      - "9200:9200"
    environment:
      discovery.type: single-node
      xpack.security.enabled: false
    volumes:
      - audiobase_elasticsearch:/usr/share/elasticsearch/data
  audiobase_kibana:
    container_name: audiobase_kibana
    image: kibana:8.11.3
    ports:
      - "5601:5601"
    depends_on: 
      - audiobase_elasticsearch
    environment:
      ELASTICSEARCH_URL: audiobase_elasticsearch:9200